# Generated by Django 3.2.9 on 2021-11-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=220)),
                ('country_logo', models.ImageField(upload_to='imgaes/')),
            ],
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=220)),
                ('last_name', models.CharField(max_length=220)),
                ('username', models.CharField(max_length=220, unique=True)),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('cover_photo', models.ImageField(upload_to='images/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.country')),
                ('professions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.professions')),
            ],
        ),
    ]
