# Generated by Django 3.2.9 on 2021-11-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0005_auto_20211109_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('group_name', models.CharField(max_length=220)),
                ('group_profile_picture', models.ImageField(upload_to='images/')),
                ('user', models.ManyToManyField(to='Account.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('EDITOR', 'EDITOR'), ('NORMAL USER', 'NORMAL USER')], max_length=220)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.usermodel')),
            ],
            options={
                'ordering': ['-user'],
            },
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('context', models.TextField()),
                ('attachments', models.FileField(upload_to='files/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GroupApp.groupmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
