# Generated by Django 3.2.9 on 2021-11-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppost',
            old_name='context',
            new_name='content',
        ),
    ]
