# Generated by Django 3.2.9 on 2021-11-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_impression',
            field=models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('OVER POSITIVE', 'OVER POSITIVE'), ('NEGATIVE', 'NEGATIVE'), ('VERY POOR', 'VERY POOR')], max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
