# Generated by Django 3.2.9 on 2021-11-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AD', '0002_auto_20211103_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='reach',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
